language: node_js
node_js:
  - "8"
services:
  - xvfb
dist: trusty

before_install:
  - google-chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - xvfb-run node nightwatch