language: node_js
node_js:
  - "8"
services:
  - xvfb
dist: trusty
addons:
  chrome: beta
before_install:
  - google-chrome-beta --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  - xvfb-run node nightwatch